package main

import (
	"bytes"
	"fmt"
	"go/format"
)

type generatorConfig struct {
	PackageName           string
	RegistrarName         string
	Appenders             []pluginBinding
	Layouts               []pluginBinding
	Filters               []pluginBinding
	Lookups               []pluginBinding
	JSONTemplateResolvers []pluginBinding
}

func generatePluginRegistrar(config generatorConfig) ([]byte, error) {
	if err := config.validate(); err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by goark-log-plugin-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", config.PackageName)
	buf.WriteString("import goarklog \"goark.dev/log\"\n\n")
	fmt.Fprintf(&buf, "// %s 返回当前包的 goark-log 插件注册器。\n", config.RegistrarName)
	fmt.Fprintf(&buf, "func %s() goarklog.PluginRegistrar {\n", config.RegistrarName)
	buf.WriteString("\treturn goarklog.NewPluginSet(\n")
	writeBindings(&buf, "WithPluginAppender", config.Appenders)
	writeBindings(&buf, "WithPluginLayout", config.Layouts)
	writeBindings(&buf, "WithPluginFilter", config.Filters)
	writeBindings(&buf, "WithPluginLookup", config.Lookups)
	writeBindings(&buf, "WithPluginJSONTemplateResolver", config.JSONTemplateResolvers)
	buf.WriteString("\t)\n")
	buf.WriteString("}\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated registrar: %w", err)
	}
	return formatted, nil
}

func writeBindings(buf *bytes.Buffer, optionName string, bindings []pluginBinding) {
	for _, binding := range bindings {
		fmt.Fprintf(buf, "\t\tgoarklog.%s(%q, %s),\n", optionName, binding.Kind, binding.Factory)
	}
}

func (c generatorConfig) validate() error {
	if !isPackageName(c.PackageName) {
		return fmt.Errorf("package name %q is invalid", c.PackageName)
	}
	if !isGoIdentifier(c.RegistrarName) || goKeywords[c.RegistrarName] {
		return fmt.Errorf("registrar name %q is invalid", c.RegistrarName)
	}
	if !c.hasBindings() {
		return fmt.Errorf("at least one plugin binding is required")
	}
	for _, group := range []struct {
		name     string
		bindings []pluginBinding
	}{
		{name: "appender", bindings: c.Appenders},
		{name: "layout", bindings: c.Layouts},
		{name: "filter", bindings: c.Filters},
		{name: "lookup", bindings: c.Lookups},
		{name: "json-template-resolver", bindings: c.JSONTemplateResolvers},
	} {
		if err := validateBindings(group.name, group.bindings); err != nil {
			return err
		}
	}
	return nil
}

func (c generatorConfig) hasBindings() bool {
	return len(c.Appenders)+
		len(c.Layouts)+
		len(c.Filters)+
		len(c.Lookups)+
		len(c.JSONTemplateResolvers) > 0
}

func validateBindings(name string, bindings []pluginBinding) error {
	for index, binding := range bindings {
		if binding.Kind == "" {
			return fmt.Errorf("%s binding %d kind is empty", name, index)
		}
		if !isGoSelector(binding.Factory) {
			return fmt.Errorf("%s binding %d factory %q is invalid", name, index, binding.Factory)
		}
	}
	return nil
}
